# .air.toml

[build]
# Command to build the binary. Ensure it points to the correct Go file.
cmd = "go build -o /app/ehass ./cmd/server"
# Path to the binary. It should match the output of the build command.
bin = "/app/ehass"
# Full binary path. This is where Air will look for the binary.
full_bin = "/app/ehass"
# Include extensions to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]
# Exclude directories to prevent unnecessary rebuilds
exclude_dir = ["vendor", "test", "scripts", "deployments"]

[log]
# Enable timestamp in logs
time = true

[color]
# Color settings for the main log output
main = "yellow"
