# deployments/docker/Dockerfile.prod
ARG GO_VERSION=1.24
FROM golang:${GO_VERSION} AS prod

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Force Linux build with static linking
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o curawize_backend ./cmd/server

EXPOSE 8080
CMD ["./curawize_backend"]
