server:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s
  idleTimeout: 60s
  baseURL: http://localhost:8080

database:
  driver: postgres
  host: postgres
  port: 5432
  user: ehass_user
  password: ehass_password
  name: ehass_db
  sslmode: disable
  maxOpen: 25
  maxIdle: 5
  lifetime: 5m

auth:
  accessTokenSecret: your-access-token-secret-key-here
  refreshTokenSecret: your-refresh-token-secret-key-here
  accessTokenExpiry: 1h
  refreshTokenExpiry: 168h

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

oauth:
  github:
    clientID: your-github-client-id-here
    clientSecret: your-github-client-secret-here
    redirectURL: http://localhost:8080/api/v1/auth/github/callback
  google:
    clientID: your-google-client-id-here
    clientSecret: your-google-client-secret-here
    redirectURL: http://localhost:8080/api/v1/auth/google/callback

email:
  smtpHost: smtp.example.com
  smtpPort: 587
  smtpUsername: your-smtp-username-here
  smtpPassword: your-smtp-password-here
  fromEmail: noreply@ehass.com